language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
install:
  - npm install -g --silent firebase-tools
  - npm install
script:
  - echo "Building and Deploying to Firebase Hosting"
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
branches:
  only:
    - master
